[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[window]
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
